### PR TITLE
removed approveAndCall from HumanStandardToken.sol

### PR DESCRIPTION
**Pull request by barryWhiteHat**
I don't like this functionality. I don't think it belongs in MVP. It may also complicate reviewing the rest of the contract. That remains to be seen. But any objection to removing it?

### CODE REVIEW

**Comment by GriffGreen** [comment]
I also hate this function... mostly because its not very readible for normal people.... i am always down for less is more.

**Comment by GriffGreen** [comment]
Kill it! :-)

**Comment by jbaylina** [comment]
It's not strictly part of the ERC20 specification, but it's becoming a de facto standard, the same way that the name, symbol or precission of the token. 
It saves one transaction in the tipical call and approve sequence. 
This procedure is in the standard Contract implemetation. 
So for all that, I would maintain it.

**Comment by barryWhiteHat** [comment]
This is equivalent to calling `approve` and then any other function afterwards. Right now i can see no negative effects from it. Tho it is a little complicated to understand. 

My philosophy is that complexity like this should live in the user interface. Is the only function of this to make things easier for users? If so I would rather remove it for this philosophical reason. As I want to be ruthless in keeping down complexity in Contract land. Where possible complexity should live in the User interface.

**Comment by jbaylina** [comment]
I commented this function

**Pull request closed without merging**
